/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trackerapp.forms;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import trackerapp.Activity;
import trackerapp.Lists.ActivityList;

/**
 *
 * @author micle
 */
public class ActivityLogsForm extends javax.swing.JFrame {

    DefaultListModel[] listModels;
    JList<String>[] lists;
    
    
    ActivityList activityList;
    /**
     * Creates new form CarGUI
     */
    public ActivityLogsForm() {
        
        initComponents();
       
        
        lists = new JList[7];
        lists[0] = mondayActivities;
        lists[1] = tuesdayActivities;
        lists[2] = wednesdayActivities;
        lists[3] = thursdayActivities;
        lists[4] = fridayActivities;
        lists[5] = saturdayActivities;
        lists[6] = sundayActivities;
        
        
        
        activityList = ActivityList.getInstance();
        
        for(int i = 0;i < 7;i++){
            loadActivities(i);
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mondayActivities = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tuesdayActivities = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        wednesdayActivities = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        thursdayActivities = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        fridayActivities = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        saturdayActivities = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        sundayActivities = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Activities");

        jLabel2.setLabelFor(mondayActivities);
        jLabel2.setText("Monday");

        jLabel3.setLabelFor(tuesdayActivities);
        jLabel3.setText("Tuesday");

        jLabel4.setLabelFor(wednesdayActivities);
        jLabel4.setText("Wednesday");

        jLabel5.setLabelFor(thursdayActivities);
        jLabel5.setText("Thursday");

        jLabel6.setLabelFor(fridayActivities);
        jLabel6.setText("Friday");

        jLabel7.setLabelFor(saturdayActivities);
        jLabel7.setText("Saturday");

        jLabel8.setLabelFor(sundayActivities);
        jLabel8.setText("Sunday");

        mondayActivities.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        mondayActivities.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mondayActivitiesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mondayActivities);

        tuesdayActivities.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        tuesdayActivities.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tuesdayActivitiesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tuesdayActivities);

        wednesdayActivities.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        wednesdayActivities.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wednesdayActivitiesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(wednesdayActivities);

        thursdayActivities.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        thursdayActivities.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thursdayActivitiesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(thursdayActivities);

        fridayActivities.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        fridayActivities.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fridayActivitiesMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(fridayActivities);

        saturdayActivities.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        saturdayActivities.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saturdayActivitiesMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(saturdayActivities);

        sundayActivities.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        sundayActivities.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sundayActivitiesMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(sundayActivities);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Click on the list you want to add an activity to");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(620, 620, 620)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(394, 394, 394)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(51, 51, 51)
                                                .addComponent(jLabel4))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(215, 215, 215)
                                                .addComponent(jLabel8)))))
                                .addGap(151, 151, 151)))))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void loadActivities(int dayOfWeek){
      // DefaultListModel listModel = listModels[dayOfWeek];
     DefaultListModel listModel = new DefaultListModel();
     
       
       listModel.clear();
         
                 for(Activity activity: activityList.getActivities()){
                     if(activity.getDayOfWeek() == dayOfWeek)
                        listModel.addElement(activity.getName());
                        
                 }
                 
                 lists[dayOfWeek].setModel(listModel);            
    }
     
     
    
    
    
    private void mondayActivitiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mondayActivitiesMouseClicked
            
        
        String activityName = JOptionPane.showInputDialog(null,"Please type in a monday activity");
        
        Activity activity = new Activity(activityName,0);
        
       ActivityList activities =  ActivityList.getInstance();
       activities.addActivity(activity);
       
       loadActivities(0);
    }//GEN-LAST:event_mondayActivitiesMouseClicked

    
    private void tuesdayActivitiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tuesdayActivitiesMouseClicked
        // TODO add your handling code here:
        String activityName = JOptionPane.showInputDialog(null,"Please type in a tuesday activity");
        
        Activity activity = new Activity(activityName,1);
        
       ActivityList activities =  ActivityList.getInstance();
       activities.addActivity(activity);
       
       loadActivities(1);
    }//GEN-LAST:event_tuesdayActivitiesMouseClicked

    
    
    private void wednesdayActivitiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wednesdayActivitiesMouseClicked
        
        String activityName = JOptionPane.showInputDialog(null,"Please type in a wednesday activity");
        
        Activity activity = new Activity(activityName,2);
        
       ActivityList activities =  ActivityList.getInstance();
       activities.addActivity(activity);
       
       loadActivities(2); 
    }//GEN-LAST:event_wednesdayActivitiesMouseClicked

    private void thursdayActivitiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thursdayActivitiesMouseClicked
           String activityName = JOptionPane.showInputDialog(null,"Please type in a thursday activity");
        
        Activity activity = new Activity(activityName,3);
        
       ActivityList activities =  ActivityList.getInstance();
       activities.addActivity(activity);
       
       loadActivities(3); 
    }//GEN-LAST:event_thursdayActivitiesMouseClicked

    
    private void fridayActivitiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fridayActivitiesMouseClicked
        // TODO add your handling code here:
           String activityName = JOptionPane.showInputDialog(null,"Please type in a friday activity");
        
        Activity activity = new Activity(activityName,4);
        
       ActivityList activities =  ActivityList.getInstance();
       activities.addActivity(activity);
       
       loadActivities(4);
        
    }//GEN-LAST:event_fridayActivitiesMouseClicked

    private void saturdayActivitiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saturdayActivitiesMouseClicked
        // TODO add your handling code here:
           String activityName = JOptionPane.showInputDialog(null,"Please type in a saturday activity");
        
        Activity activity = new Activity(activityName,5);
        
       ActivityList activities =  ActivityList.getInstance();
       activities.addActivity(activity);
       
       loadActivities(5);
    }//GEN-LAST:event_saturdayActivitiesMouseClicked

    private void sundayActivitiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sundayActivitiesMouseClicked
        // TODO add your handling code here:
         String activityName = JOptionPane.showInputDialog(null,"Please type in a sunday activity");
        
        Activity activity = new Activity(activityName,6);
        
       ActivityList activities =  ActivityList.getInstance();
       activities.addActivity(activity);
       
       loadActivities(6);
    }//GEN-LAST:event_sundayActivitiesMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActivityLogsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActivityLogsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActivityLogsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActivityLogsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActivityLogsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> fridayActivities;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JList<String> mondayActivities;
    private javax.swing.JList<String> saturdayActivities;
    private javax.swing.JList<String> sundayActivities;
    private javax.swing.JList<String> thursdayActivities;
    private javax.swing.JList<String> tuesdayActivities;
    private javax.swing.JList<String> wednesdayActivities;
    // End of variables declaration//GEN-END:variables
}
