/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trackerapp.forms;

import trackerapp.enums.ReminderActivity;

/**
 *
 * @author micle
 */
public class RemindersForm extends javax.swing.JFrame {

    SetReminderForm setReminderForm;
    /**
     * Creates new form RemindersForm
     */
    public RemindersForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workoutBox = new javax.swing.JCheckBox();
        drinkBox = new javax.swing.JCheckBox();
        walkBox = new javax.swing.JCheckBox();
        eatBox = new javax.swing.JCheckBox();
        cyclingBox = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        workoutBox.setText("Workout");
        workoutBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workoutBoxActionPerformed(evt);
            }
        });

        drinkBox.setText("Drink Water");
        drinkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkBoxActionPerformed(evt);
            }
        });

        walkBox.setText("Go for a walk");
        walkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walkBoxActionPerformed(evt);
            }
        });

        eatBox.setText("Eat an apple");
        eatBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eatBoxActionPerformed(evt);
            }
        });

        cyclingBox.setText("Go Cycling");
        cyclingBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cyclingBoxActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Select one or more reminders:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cyclingBox)
                    .addComponent(drinkBox)
                    .addComponent(eatBox)
                    .addComponent(workoutBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(walkBox))
                .addContainerGap(292, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(workoutBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drinkBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eatBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(walkBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cyclingBox)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void workoutBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workoutBoxActionPerformed
        // TODO add your handling code here:
        if(this.workoutBox.isSelected()){
            setReminderForm = new SetReminderForm(ReminderActivity.WORKOUT);
            setReminderForm.setLocationRelativeTo(null); 
            setReminderForm.setVisible(true);
        }else{
            
            
        }
    }//GEN-LAST:event_workoutBoxActionPerformed

    private void drinkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkBoxActionPerformed
        // TODO add your handling code here:
        if(this.drinkBox.isSelected()){
            setReminderForm = new SetReminderForm(ReminderActivity.DRINK_WATER);
            setReminderForm.setLocationRelativeTo(null); 
            setReminderForm.setVisible(true);
        }else{
            
            
        }
    }//GEN-LAST:event_drinkBoxActionPerformed

    private void walkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walkBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_walkBoxActionPerformed

    private void eatBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eatBoxActionPerformed
            // TODO add your handling code here:
            if(this.walkBox.isSelected()){
            setReminderForm = new SetReminderForm(ReminderActivity.GO_WALK);
            setReminderForm.setLocationRelativeTo(null); 
            setReminderForm.setVisible(true);
        }else{
            
            
        }
    }//GEN-LAST:event_eatBoxActionPerformed

    private void cyclingBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cyclingBoxActionPerformed
        // TODO add your handling code here:
        if(this.cyclingBox.isSelected()){
            setReminderForm = new SetReminderForm(ReminderActivity.GO_CYCLING);
            setReminderForm.setLocationRelativeTo(null); 
            setReminderForm.setVisible(true);
        }else{
            
            
        }
    }//GEN-LAST:event_cyclingBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemindersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemindersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemindersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemindersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemindersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cyclingBox;
    private javax.swing.JCheckBox drinkBox;
    private javax.swing.JCheckBox eatBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox walkBox;
    private javax.swing.JCheckBox workoutBox;
    // End of variables declaration//GEN-END:variables
}
