/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trackerapp.forms;

import java.util.ArrayList;
import trackerapp.WorkoutPlan;
import trackerapp.WorkoutPlanFilters;
import trackerapp.Lists.WorkoutPlanList;
import trackerapp.enums.WorkoutExperience;
import trackerapp.enums.WorkoutType;

/**
 *
 * @author micle
 */
public class WorkoutPlansForm extends javax.swing.JFrame {

    public WorkoutPlanFilters filters;
    public WorkoutPlanList plans;
    /**
     * Creates new form WorkoutPlans
     */
    public WorkoutPlansForm() {
        initComponents();
        
        filters = new WorkoutPlanFilters();
        
        this.beginnerRadio.setSelected(true);
        this.twoRadio.setSelected(true);
        this.calithenRadio.setSelected(true);
        
        this.plans = WorkoutPlanList.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        beginnerRadio = new javax.swing.JRadioButton();
        intermRadio = new javax.swing.JRadioButton();
        advRadio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        twoRadio = new javax.swing.JRadioButton();
        threeRadio = new javax.swing.JRadioButton();
        fiveRadio = new javax.swing.JRadioButton();
        sevenRadio = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        calithenRadio = new javax.swing.JRadioButton();
        weightRadio = new javax.swing.JRadioButton();
        searchBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WorkoutPlansForm");

        jLabel1.setText("Choose your experience level");

        buttonGroup1.add(beginnerRadio);
        beginnerRadio.setText("Beginner");
        beginnerRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginnerRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(intermRadio);
        intermRadio.setText("Intermediate");
        intermRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intermRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(advRadio);
        advRadio.setText("Advanced");

        jLabel2.setText("How many days a week do you want to workout?");

        buttonGroup2.add(twoRadio);
        twoRadio.setText("2");
        twoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoRadioActionPerformed(evt);
            }
        });

        buttonGroup2.add(threeRadio);
        threeRadio.setText("3");

        buttonGroup2.add(fiveRadio);
        fiveRadio.setText("5");

        buttonGroup2.add(sevenRadio);
        sevenRadio.setText("7");
        sevenRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenRadioActionPerformed(evt);
            }
        });

        jLabel3.setText("Choose workout type");

        buttonGroup3.add(calithenRadio);
        calithenRadio.setText("Calithenics");

        buttonGroup3.add(weightRadio);
        weightRadio.setText("Weightlifting");

        searchBtn.setText("Search Plans");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(beginnerRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intermRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(advRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sevenRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fiveRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(twoRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(threeRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calithenRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(searchBtn))
                            .addComponent(weightRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(calithenRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(weightRadio))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(beginnerRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(intermRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(advRadio))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16)
                        .addComponent(twoRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(threeRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fiveRadio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sevenRadio)
                .addGap(36, 36, 36)
                .addComponent(searchBtn)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beginnerRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginnerRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beginnerRadioActionPerformed

    private void twoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twoRadioActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        
        if(this.beginnerRadio.isSelected()){
            filters.setExperience(WorkoutExperience.BEGINNER);  
        }
        else if(this.intermRadio.isSelected()){
            filters.setExperience(WorkoutExperience.INTERMEDIATE);  
        }
        else
        {
            filters.setExperience(WorkoutExperience.ADVANCED);
        }
        
        
        
        
        if(this.twoRadio.isSelected()){
            filters.setDaysAWeek(2);  
        }
        else if(this.threeRadio.isSelected()){
            filters.setDaysAWeek(3);  
        }
        else if(this.fiveRadio.isSelected())
        {
            filters.setDaysAWeek(5);
        }
        else{
            filters.setDaysAWeek(7);
        }
        
        
        
        if(this.calithenRadio.isSelected()){
            filters.setWorkoutType(WorkoutType.CALITHENICS);  
        }
        else{
            filters.setWorkoutType(WorkoutType.WEIGHTLIFTING);
        }
        
        ArrayList<WorkoutPlan> plns = plans.getPlansByFilters(filters);
        
        
        PlansForm plansForm = new PlansForm(plns);
        plansForm.setLocationRelativeTo(null);
        plansForm.setVisible(true);
       
    }//GEN-LAST:event_searchBtnActionPerformed

    private void intermRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intermRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intermRadioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sevenRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sevenRadioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkoutPlansForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkoutPlansForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkoutPlansForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkoutPlansForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkoutPlansForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton advRadio;
    private javax.swing.JRadioButton beginnerRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton calithenRadio;
    private javax.swing.JRadioButton fiveRadio;
    private javax.swing.JRadioButton intermRadio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton searchBtn;
    private javax.swing.JRadioButton sevenRadio;
    private javax.swing.JRadioButton threeRadio;
    private javax.swing.JRadioButton twoRadio;
    private javax.swing.JRadioButton weightRadio;
    // End of variables declaration//GEN-END:variables
}
